// All routes for SSG pre-rendering
export const routes = [
  '/',
  '/about-us',
  '/meet-dr-zach',
  '/pediatric',
  '/prenatal',
  '/family',
  '/new-patient-center',
  '/new-patient-forms',
  '/request-an-appointment',
  '/schedule-appointment',
  '/book-appointment',
  '/events-workshops',
  '/contact-us',
  '/privacy',
  '/thanks',
  '/3-ways-to-poop',

  '/rhkn-guide',
  '/3-ways-to-sleep',
  '/free-guides-for-parents',
  '/talsky-tonal-chiropractic',
  '/insight-scans',
  '/answers',
];
